# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cYQgJw1eMD2LZrEbFtDuVn6lMtoru1A4
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv('SentimentDataset.csv')

# Basic info
print("Dataset Summary:\n")
print(df.info())
print("\nFirst 5 rows:\n")
print(df.head())

# Check for missing values
print("\nMissing values:\n", df.isnull().sum())

# Drop rows with missing values (optional)
df.dropna(inplace=True)

# Sentiment distribution
print("\nSentiment distribution:\n", df['Sentiment'].value_counts())

# Plot sentiment distribution
plt.figure(figsize=(8, 5))
sns.countplot(data=df, x='Sentiment', palette='Set2')
plt.title("Sentiment Label Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# Word cloud of most common words (optional)
from wordcloud import WordCloud

text_data = ' '.join(df['Text'].astype(str))
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text_data)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Common Words in Text")
plt.show()